FROM golang:1.20-alpine3.17 AS envbuild
WORKDIR tools
USER root
RUN go env -w GO111MODULE=on
RUN go version
RUN apk update
RUN apk add sudo
RUN apk add git
RUN go mod init golibri
RUN go get github.com/derivaro/golibri
